[game]
hostname = "ğŸŒ† Backmen [TTS]"
desc = """
               ğŸŒŒâœ¨ ğ—•ğ—®ğ—°ğ—¸ğ—ºğ—²ğ—» & ğ—”ğ˜ğ—®ğ—¿ğ—®ğ˜…ğ—¶ğ—® âœ¨ğŸŒŒ
              ğŸŒ† ĞœĞµÑÑ‚Ğ¾ Ğ´Ğ»Ñ Ğ²Ğ°ÑˆĞ¸Ñ… Ğ¸ÑÑ‚Ğ¾Ñ€Ğ¸Ğ¹! ğŸŒ†
â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  ğŸ—£ï¸  TTS: ĞŸĞ¾Ğ´Ğ´ĞµÑ€Ğ¶Ğ¸Ğ²Ğ°ĞµÑ‚ Ğ¼Ğ½Ğ¾Ğ¶ĞµÑÑ‚Ğ²Ğ¾ Ñ€Ğ°Ğ·Ğ»Ğ¸Ñ‡Ğ½Ñ‹Ñ… Ğ³Ğ¾Ğ»Ğ¾ÑĞ¾Ğ².
  ğŸ¤¯  ĞšÑƒĞ»ÑŒÑ‚ Ğ¿Ğ»Ğ¾Ñ‚Ğ¸: Ğ£Ğ½Ğ¸ĞºĞ°Ğ»ÑŒĞ½Ñ‹Ğ¹ ĞºÑƒĞ»ÑŒÑ‚, Ñ€Ğ°ÑÑˆĞ¸Ñ€ÑÑÑ‰Ğ¸Ğ¹ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚Ğ¸ Ğ´Ğ»Ñ Ğ¸Ğ³Ñ€Ñ‹.
  ğŸŒ¬ï¸  Ğ‘Ğ»Ğ¾Ğ±: ĞŸÑ€ĞµĞ²Ñ€Ğ°Ñ‚Ğ¸ÑÑŒ Ğ² ÑĞ³ÑƒÑÑ‚Ğ¾Ğº Ğ¼Ğ°ÑÑÑ‹ Ğ¸ ÑƒĞ½Ğ¸Ñ‡Ñ‚Ğ¾Ğ¶ÑŒ ÑÑ‚Ğ°Ğ½Ñ†Ğ¸Ñ 28 ÑĞ¿Ğ¾ÑĞ¾Ğ±Ğ°Ğ¼Ğ¸.
  ğŸ˜  ĞĞ¿ĞµĞ½ÑÑƒÑ€Ñ: Ğ›ÑĞ±Ğ¾Ğ¹ Ğ¼Ğ¾Ğ¶ĞµÑ‚ Ğ²Ğ»Ğ¾Ğ¶Ğ¸Ñ‚ÑŒ ÑĞ²Ğ¾Ğ¹ Ğ²ĞºĞ»Ğ°Ğ´!
â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
"""
map_pool = "DefaultMapPool"
maxplayers = 100
soft_max_players = 30
map_rotation = true
fallbackpreset = "Traitor,Extended"
lobbyenabled = true
role_timers = true

[game]
contraband_examine = false
diagonalmovement = true

[tips]
tips.enabled = false

[salvage]
expedition_cooldown = 300f

[ic]
flavor_text = true
punctuation = true

[ooc]
enable_during_round = true
show_ooc_patron_color = false

[looc]
enabled_crit = true

[emergency]
emergency_early_launch_allowed = true
emergency_dock_time = 280f
emergency_authorize_time = 30f
auto_call_time = 150
auto_call_extension_time = 70

[biomass]
easy_mode = false

[chat]
max_message_length = 5000
max_announcement_length = 1200

[atmos]
space_wind = false
space_wind_max_velocity = 22.0
monstermos_rip_tiles = false

[shuttle]
arrivals_map = "/Maps/Misc/corvax_terminal.yml"
emergency = true
arrivals = true

[gpt]
enabled = false

[queue]
enabled = false

[discord auth]
auth.enabled = false

[glimmer]
enabled = true

[tts]
token = ""
api_url = ""

[infolinks]
discord = "https://discord.gg/ss-14-backmen-ru-1053200453829132298"
github = "https://github.com/Rxup/space-station-14"
wiki = "https://wiki.backmen.ru"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
preset_enabled = false
restart_enabled = false
