# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 18000 #5 hrs # Corvax-RoleTime
#    - !type:RoleTimeRequirement
#      role: JobMedicalDoctor
#      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 #15 hrs # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
    - !type:AgeRequirement
      requiredAge: 21
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance
      flatBonus: 0.025
    - type: NpcFactionMember
      factions:
      - CentralCommand
    - type: CommandStaff
    #start-backmen: surgery
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 2.5
    #end-backmen: surgery
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
