- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 25
  #end-backmen: currency

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalInternChameleonOutfit
  job: MedicalIntern
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesLatex
