- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 25
  #end-backmen: currency

- type: startingGear
  id: MedicalInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
