- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 2.5h
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 50
  #end-backmen: currency
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
