- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 #4 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 35
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
    #start-backmen: surgery
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      SpeedModifier: 1.75
    #end-backmen: surgery

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
