- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 3600 # 1 hrs # Astroplex-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs # Astroplex-RoleTime
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 35
  #end-backmen: currency

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackParamedicFilled
    shoes: ClothingShoesColorBlue
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
  innerClothingSkirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelParamedicFilled
  duffelbag: ClothingBackpackDuffelParamedicFilled
