- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 216000 # 60 hrs
  startingGear: SeniorPhysicianGear
  icon: "SeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  #start-backmen: currency
  minBankBalance: 300
  maxBankBalance: 600
  wageDepartment: Medical
  wage: 135
  #end-backmen: currency

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
