- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
  startingGear: BrigmedicGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Medical
    - Security
    - Brig
    - Maintenance
    - External
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 50
  #end-backmen: currency
  special:
    - !type:AddComponentSpecial
      components:
        - type: PsionicBonusChance
          flatBonus: 0.025
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    back: ClothingBackpackBrigmedicFilled # Backmen
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretSecurityMedic # Corvax-Resprite
    outerClothing: ClothingOuterVestArmorMedSec # Corvax-Resprite
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic # Backmen
    mask: ClothingMaskSterile
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
