- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
  startingGear: BrigmedicGear
  icon: "Brigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
    - Medical
    - Security
    - Brig
    - Maintenance
    - External
  #start-backmen: currency
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Security
  wage: 100
  #end-backmen: currency

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretSecurityMedic # Corvax-Resprite
    outerClothing: ClothingOuterVestArmorMedSec # Corvax-Resprite
    id: BrigmedPDA
    ears: ClothingHeadsetSecurity
    mask: ClothingMaskSterile
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
