- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs # Corvax-RoleTime
  - !type:AgeRequirement
      requiredAge: 21 # cats
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
    #start-backmen: currency
  minBankBalance: 200
  maxBankBalance: 300
  wageDepartment: Security
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolster
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    belt:
    - SpeedLoaderMagnum

