- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #50 hrs # Corvax-RoleTime
  startingGear: WardenGear
  icon: "JobIconWarden"
  requireAdminNotify: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 50
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    pda: WardenPDA
    ears: ClothingHeadsetSecurity
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - Flash
