- type: job
  id: BKCCOperator
  name: job-name-centcomoper
  description: job-description-centcomoper
  playTimeTracker: JobCentralCommandOperator
  setPreference: true
  startingGear: OperatorGavna
  icon: JobIconNanotrasen
  supervisors: job-supervisors-hoh
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelistRequired: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobSAI
      time: 18000
    - !type:RoleTimeRequirement
      role: JobCentralCommandAssistant
      time: 21600
    - !type:DepartmentTimeRequirement
      department: CentCom
      time: 43200
  access:
    - CCCargo
    - CCSecurity
    - CentralCommand
    - CCOfficer
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: SpecForce
          actionBssActionName: ActionCentcomFtlAction
        - type: Psionic
        - type: DispelPower
        - type: InitialInfectedExempt
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: CentCom
  wage: 75

- type: startingGear
  id: OperatorGavna
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomVeryOfficial
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: CCOperatorPDA
    ears: ClothingHeadsetCentCom
    pocket1: ClothingMaskGasCentcom
  innerClothingSkirt: ClothingUniformJumpskirttCentcomVeryOfficial
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: entity
  parent: CentcomPDABackmen
  id: CCOperatorPDA
  name: Centcom Operator PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Pda
      id: IDCardCentComGavnaOperator
      state: pda-centcom
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      state: pda-centcom

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComGavnaOperator
  name: Id карта оператора ЦК
  components:
    - type: PresetIdCard
      job: BKCCOperator
    - type: Access
      tags:
        - CCCargo
        - CCSecurity
        - CentralCommand
        - CCOfficer
      groups:
        - AllAccess
