- type: department
  id: CentCom
  name: department-CentCom
  description: department-CentCom-description
  color: "#13db0f"
  primary: true
  weight: -5
  roles:
    - BKCCSecGavna
    - BKCCSecOfficer
    - BKCCOperator
    - BKCCOfficial
    - BKCCCargo
    - BKCCAssistant
    - BKCCAdmiral
    - BlueShield
  accountNumber: 1350  #backmen: currency
