- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs # Corvax-RoleTime
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Engineering
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackAtmosphericsFilled
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelAtmosphericsFilled
  duffelbag: ClothingBackpackDuffelAtmosphericsFilled
