- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    pda: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

