- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  accountNumber: 1315 #backmen: currency

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - Detective
  - ServiceWorker
  #- TechnicalAssistant "The job TechnicalAssistant has more than 1 primary department!"
  #- ResearchAssistant
  accountNumber: 1316 #backmen: currency

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - IAA # Corvax-IAA
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - SAI
  accountNumber: 1317 #backmen: currency
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant
  accountNumber: 1318 #backmen: currency

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  accountNumber: 1319 #backmen: currency

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Warden
  - Brigmedic #backmen
  - Prisoner #backmen
  accountNumber: 1320  #backmen: currency

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - Roboticist         #backmen: currency
  - Scientist
  - ResearchAssistant
  accountNumber: 1321  #backmen: currency

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  accountNumber: 1322  #backmen: currency
  primary: false
