- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 35
  #end-backmen: currency

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackPsychologistFilled # Corvax-Stamp
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  innerClothingSkirt: ClothingUniformJumpskirtPsychologist # Corvax-Resprite
  satchel: ClothingBackpackSatchelPsychologistFilled # Corvax-Stamp
  duffelbag: ClothingBackpackDuffelPsychologistFilled # Corvax-Stamp
