- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 35
  #end-backmen: currency

- type: startingGear
  id: PsychologistGear
  equipment:
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist
