- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: ReporterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpsuitJournalist
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
