- type: job
  id: Zookeeper
  name: job-name-zookeeper
  description: job-description-zookeeper
  playTimeTracker: JobZookeeper
  startingGear: ZookeeperGear
  icon: "Zookeeper"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  #start-backmen: currency
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Civilian
  wage: 100
  #end-backmen: currency

- type: startingGear
  id: ZookeeperGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSafari
    back: ClothingBackpackFilled
    head: ClothingHeadSafari
    shoes: ClothingShoesColorWhite
    id: ZookeeperPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpsuitSafari
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
