- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
#    - !type:RoleTimeRequirement
#      role: JobCargoTechnician
#      time: 21600 #6 hrs
#    - !type:RoleTimeRequirement
#      role: JobSalvageSpecialist
#      time: 3600 #_Ck
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 3600 #_Ck
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - Command
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Cargo
  wage: 50
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelQuartermasterFilled
  duffelbag: ClothingBackpackDuffelQuartermasterFilled
