- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobPilot
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs
  startingGear: PilotGear
  icon: "JobIconPilot"
  supervisors: job-supervisors-hos
  canBeAntag: false
  #start-backmen: currency
  minBankBalance: 1500
  maxBankBalance: 2500
  wageDepartment: Security
  wage: 500
  #end-backmen: currency
  access:
  - Security
  - Brig
  - Maintenance
  - Engineering #backmen
  - Atmospherics #backmen
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PilotGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: PilotPDA
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat #backmen
    pocket1: WeaponMultiphaseEnergyGun #backmen
    pocket2: RadioSecurityPilotSupplyPod #backmen
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - SecPilotSetLoadouts #backmen
   #- MagazinePistol  (backmen)
