- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleXenoAgent
  name: Xeno Agent Role
  #  description: mind-role-blob-description
  components:
  - type: MindRole
    antagPrototype: XenoAgent
    exclusiveAntag: true
  - type: XenoAgentRole

# Blob
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBlob
  name: Blob Role
#  description: mind-role-blob-description
  components:
  - type: MindRole
    antagPrototype: Blob
    exclusiveAntag: true
  - type: BlobRole

# Bloodsucker
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodsucker
  name: Bloodsucker Role
#  description: mind-role-bloodsucker-description
  components:
  - type: MindRole
    antagPrototype: Bloodsucker
    exclusiveAntag: true
  - type: VampireRole

# Changeling
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
#  description: mind-role-changeling-description
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
  - type: ChangelingRole

# EvilTwin
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEvilTwin
  name: Evil Twin Role
#  description: mind-role-evil-twin-description
  components:
  - type: MindRole
    antagPrototype: EvilTwin
    exclusiveAntag: true
  - type: EvilTwinRole

# SuperPsi
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSuperPsi
  name: Super Psi Role
#  description: mind-role-super-psi-description
  components:
  - type: MindRole
    antagPrototype: SuperPsi
    exclusiveAntag: true
  - type: SuperPsiRole

# Fugitive
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive Role
#  description: mind-role-fugitive-description
  components:
  - type: MindRole
    antagPrototype: Fugitive
    exclusiveAntag: true
  - type: FugitiveRole

# Bank
- type: entity
  parent: BaseMindRole
  id: MindRoleBankMemory
  name: Bank Memory
  #  description: mind-role-fugitive-description
  components:
  - type: MindRole
  - type: BankMemory
