- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access: # Corvax-MRP
  - Maintenance
  #start-backmen: currency
  minBankBalance: 50
  maxBankBalance: 400
  #end-backmen: currency

- type: startingGear
  id: PassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  innerClothingSkirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
