- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: ChefGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    head: ClothingHeadHatChef
    back: ClothingBackpackFilled
    mask: ClothingMaskItalianMoustache
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronChef
    belt: ClothingBeltChefFilled
  innerClothingSkirt: ClothingUniformJumpskirtChef
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
