- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 #1 hrs # Corvax-RoleTime
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency
  special: # Goobstation - Martial Arts
  - !type:AddComponentSpecial # Goobstation - Martial Arts
    components: # Goobstation - Martial Arts
      - type: GrantCqc # Goobstation - Martial Arts
        isBlocked: true # Goobstation - Martial Arts

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
