- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  startingGear: JanitorGear
  icon: "JobIconJanitor"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Civilian
  wage: 50
  #end-backmen: currency

- type: startingGear
  id: JanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    pda: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
    id: Wallet # space cats add_id_revork
  #storage:
    #back:
    #- Stuff

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    pda: JanitorPDA
    gloves: ClothingHandsGlovesJanitor
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
    id: Wallet # space cats add_id_revork
