- type: latheRecipe
  id: ClothingHeadHelmetInsulated
  result: ClothingHeadHelmetInsulated
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: InsulativeHeadcage
  icon:
    sprite: Backmen/Clothing/Head/Hats/cage.rsi
    state: icon
  result: ClothingHeadCage
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ShellSoulbreaker
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: practice
  result: ShellSoulbreaker
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Bluespace: 10
    Glass: 5

- type: latheRecipe
  id: EnergyDomeDirectionalTurtle
  result: EnergyDomeDirectionalTurtle
  completetime: 12
  materials:
    Steel: 1000
    Plastic: 500
    Gold: 250
    Uranium: 50

- type: latheRecipe
  id: SecurityCyberneticEyes
  result: SecurityCyberneticEyes
  categories:
  -  Robotics
  completetime: 5
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500
    Gold: 300
    Silver: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol9x17
  result: MagazinePistol9x17
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGun57x28
  result: MagazinePistolSubMachineGun57x28
  materials:
    Steel: 350

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunVector45ACP
  result: MagazinePistolSubMachineGunVector45ACP
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGun9x17
  result: MagazinePistolSubMachineGun9x17
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolTopSubMachineGun
  result: MagazinePistolTopSubMachineGun
  materials:
    Steel: 475

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleFamas556UEG
  result: MagazineRifleFamas556UEG
  materials:
    Steel: 475

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle556UEG
  result: MagazineRifle556UEG
  materials:
    Steel: 475

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle762UEG
  result: MagazineRifle762UEG
  materials:
    Steel: 475

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle762UEGIncendiary
  result: MagazineRifle762UEGIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleFamas556UEGIncendiary
  result: MagazineRifleFamas556UEGIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifle556UEGIncendiary
  result: MagazineRifle556UEGIncendiary
  materials:
    Steel: 25
    Plastic: 450

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol45ACP
  result: MagazinePistol45ACP
  materials:
    Steel: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol45ACPincendiary
  result: MagazinePistol45ACPincendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol9x17Incendiary
  result: MagazinePistol9x17Incendiary
  materials:
    Steel: 20
    Plastic: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol57x28
  result: MagazinePistol57x28
  materials:
    Steel: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol57x28Incendiary
  result: MagazinePistol57x28Incendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol57x28Extd
  result: MagazinePistol57x28Extd
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxHeavyRifle
  result: MagazineBoxHeavyRifle
  materials:
    Steel: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762x39
  result: MagazinePacketRifle762x39
  materials:
    Steel: 900

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762UEG
  result: MagazinePacketRifle762UEG
  materials:
    Steel: 750

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistolACP
  result: MagazinePacketPistolACP
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol9x17
  result: MagazinePacketPistol9x17
  materials:
    Steel: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol57x28
  result: MagazinePacketPistol57x28
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol50AE
  result: MagazinePacketPistol50AE
  materials:
    Steel: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistolACPIncendiary
  result: MagazinePacketPistolACPIncendiary
  materials:
    Steel: 100
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol9x17Incendiary
  result: MagazinePacketPistol9x17Incendiary
  materials:
    Steel: 100
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol57x28Incendiary
  result: MagazinePacketPistol57x28Incendiary
  materials:
    Steel: 100
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762x39Incendiary
  result: MagazinePacketRifle762x39Incendiary
  materials:
    Steel: 1000
    Plastic: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762UEGIncendiary
  result: MagazinePacketRifle762UEGIncendiary
  materials:
    Steel: 1000
    Plastic: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle556UEGIncendiary
  result: MagazinePacketRifle556UEGIncendiary
  materials:
    Steel: 1000
    Plastic: 1000

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketPistol50AEAP
  result: MagazinePacketPistol50AEAP
  materials:
    Steel: 2000
    Plasteel: 1000
    Diamond: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762x39AP
  result: MagazinePacketRifle762x39AP
  materials:
    Steel: 3000
    Plasteel: 1500
    Diamond: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle556UEGAP
  result: MagazinePacketRifle556UEGAP
  materials:
    Steel: 2000
    Plasteel: 1200
    Diamond: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePacketRifle762UEGAP
  result: MagazinePacketRifle762UEGAP
  materials:
    Steel: 1500
    Plasteel: 1100
    Diamond: 500
