- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
#  requirements:
#    - !type:OverallPlaytimeRequirement
#      time: 3600 #1 hrs #_Ck
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
