- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs # Astroplex-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        multiplier: 3
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatRD
    id: RnDPDA
    ears: ClothingHeadsetRD
  inhand:
    - Baton
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
