- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-objective
  guides: [ Changelings ]
  discordRequired: true # backmen: antag
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h
