- type: job
  id: BKCCSecGavna
  name: job-name-centcomSecGavna
  description: job-description-centcomSecGavna
  playTimeTracker: JobCentralCommandSecGavna
  setPreference: true
  startingGear: HeadOfSecurityCentComGear
  icon: JobIconCCHeadOfSecurity
  supervisors: job-supervisors-hoh
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  whitelisted: true
  discordRequired: true
  requirements:
    - !type:RoleTimeRequirement
      role: JobCentralCommandAssistant
      time: 21600
    - !type:DepartmentTimeRequirement
      department: CentCom
      time: 43200
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 18000
    - !type:RoleTimeRequirement
      role: JobCentralCommandSecOfficer
      time: 18000
  access:
    - CentralCommand
    - CCSecurity
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: SpecForce
          actionBssActionName: ActionCentcomFtlAction
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: Psionic
        - type: PyrokinesisPower
        - type: AntagImmune
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: CentCom
  wage: 75

- type: jobIcon
  parent: JobIcon
  id: JobIconCCHeadOfSecurity
  icon:
    sprite: /Textures/Backmen/Icons/jobicon.rsi
    state: Security

- type: startingGear
  id: HeadOfSecurityCentComGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomMilitary
    back: ClothingCentcomBackpack
    shoes: ClothingShoesBootsCentcom
    mask: ClothingMaskGasSecurity
    neck: CombatKnifeSpetsnaz
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorCentcom
    suitstorage: WeaponRifleFamas
    head: ClothingHeadHatBeretHoSCentcom
    id: CCOfficerPDA
    ears: ClothingHeadsetCentComCC
    belt: ClothingBeltSecuritySuper
    pocket1: WeaponPistolG23
    pocket2: MagazinePistol
  storage:
    back:
    - MedkitCombatFilled
    - BoxSurvivalSecurity
    - MagazineRifle

- type: entity
  parent: OrdenPDA
  id: CCOfficerPDA
  name: Centcom Officer PDA
  description: Black with green lines, sign of the walking protection of the bureaucracy.
  components:
    - type: Appearance
      appearanceDataInit:
        enum.PdaVisuals.PdaType:
          !type:String
          pda-centcomsec
    - type: Pda
      id: IDCardCentComGavnaOfficerSesurity
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#5B5B5B"
    - type: Icon
      state: pda-centcomsec

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComGavnaOfficerSesurity
  name: ID Начальника Безопасности ЦК
  components:
    - type: Sprite
      layers:
      - state: silver
      - state: idsecurityofficer
    - type: Item
      heldPrefix: silver
    - type: PresetIdCard
      job: BKCCSecGavna
    - type: Access
      tags:
        - CCSecurity
        - CentralCommand
      groups:
        - AllAccess
