- type: job
  id: BKCCAssistant
  name: job-name-centcomassistant
  description: job-description-centcomassistant
  playTimeTracker: JobCentralCommandAssistant
  setPreference: true
  startingGear: CentComInternGear
  icon: JobIconServiceWorker
  supervisors: job-supervisors-centcommembers
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  discordRequired: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 108000
  access:
    - CentralCommand
    - Service
    - Maintenance
    - Bar
    - Kitchen
    - Hydroponics
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: SpecForce
          actionBssActionName: ActionCentcomFtlAction
        - type: NpcFactionMember
          factions:
            - CentralCommand
        - type: PsionicBonusChance
          multiplier: 3
        - type: AntagImmune
  minBankBalance: 100
  maxBankBalance: 250
  wageDepartment: CentCom
  wage: 75

- type: startingGear
  id: CentComInternGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomIntern
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: CentcomInternPDABackmen
    ears: ClothingHeadsetCentCom

- type: startingGear
  id: CentComInternGearArmed # POWER IN QUANTITY!
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomIntern
    back: WeaponSniperMosinNew
    shoes: ClothingShoesColorBlack
    eyes: ClothingEyesGlassesSunglasses
    neck: CombatKnifeSpetsnaz
    id: CentcomInternPDABackmen
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatCorpsoft
    pocket1: MedicatedSuture
    pocket2: MagazineBoxLightRifle
    outerClothing: ClothingOuterArmorBasic

- type: entity
  parent: BasePDA
  id: CentcomInternPDABackmen
  name: CentCom Assistant PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Appearance
      appearanceDataInit:
        enum.PdaVisuals.PdaType:
          !type:String
          pda-centcom
    - type: Pda
      id: IDCardCentComIntern
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      state: pda-centcom

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComIntern
  name: ID карта Ассистента ЦК
  components:
    - type: Sprite
      layers:
      - state: card_centcom # Backmen
      - state: sub_department # Backmen
        color: "#0F4162"
      - state: frame_head # Backmen
        color: "#0F4162"
      - state: assigned_centcom # Backmen
      - state: idintern-service
    - type: PresetIdCard
      job: BKCCAssistant
    - type: Access
      tags:
        - CentralCommand
        - Service
        - Maintenance
        - Bar
        - Kitchen
        - Hydroponics
