- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHeadCage # backmen
        amount: 2
      - id: BookSpaceLaw
      - id: ClothingHeadHatCapWardenAlt # Corvax-SecFashion
      - id: ClothingOuterCoatWardenAlt # Corvax-SecFashion
      - id: ClothingBackpackWarden # Corvax-SecFashion
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingHeadHatWarden
      - id: ClothingHeadHatBeretWarden
      - id: ClothingHeadHatCapWardenAlt # Corvax-SecFashion
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: ClothingOuterCoatWardenAlt # Corvax-SecFashion
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: ClothingEyesHudSecurity
      - id: ClothingHeadCage # backmen
        amount: 2
      - id: BookSpaceLaw
      - id: ClothingBackpackWarden # Corvax-SecFashion
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: Eftpos # backmen
      - id: FlashlightSeclite
        prob: 0.8
      - id: WeaponDisabler
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: ClothingOuterCoatSecurityOvercoat # Corvax-SecFashion
        prob: 0.2
      - id: ClothingEyesHudSecurity
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: BookSpaceLaw
        prob: 0.5

# backmen brigmedic's locker reworked
- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
        prob: 0.1
      - id: MedkitFilled
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        prob: 0.4
      - id: MedkitBruteFilled
        prob: 0.4
      - id: MedkitToxinFilled
        prob: 0.4
      - id: MedkitBurnFilled
        prob: 0.4
      - id: ClothingHeadCage # backmen
      - id: ClothingHeadsetAltBrigmedic # backmen

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        prob: 0.3
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: BookBusido # Corvax-Books
      - id: ClothingHeadCage # backmen
        amount: 1
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      - id: Wirecutter
      - id: Screwdriver
      - id: Multitool
        prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolACP14
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleAR18
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunVectorSpecial
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgun39
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotguntrenchgun4034
      amount: 2
    - id: BoxLethalshot
      amount: 2

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  name: wt550 safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunMP5
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeLaserCarbine
  name: laser safe
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: WeaponEarthGovLaserRifle
      amount: 3
