- type: technology
  id: RiotControl
  name: ataraxia-research-technology-riot-control
  icon:
    sprite: Objects/Weapons/Guns/Battery/particle_decelerator.rsi
    state: base
  discipline: RiotControl
  tier: 1
  cost: 7500
  recipeUnlocks:
  - WeaponDisabler
  - HoloprojectorField
  - MagazineShotgunBeanbag
  - BoxBeanbag

- type: technology
  id: RiotControlAdvanced
  name: ataraxia-research-technology-riot-control-advanced
  icon:
    sprite: Objects/Weapons/Melee/truncheon.rsi
    state: icon
  discipline: RiotControl
  tier: 1
  cost: 8000
  recipeUnlocks:
  - Truncheon
  - TelescopicShield
  - HoloprojectorSecurity
  - BoxShellTranquilizer
  - WeaponDisablerSMG
  technologyPrerequisites:
  - RiotControl

- type: technology
  id: WarCrimes
  name: ataraxia-research-technology-war-crimes
  icon:
    sprite: Clothing/Back/Backpacks/electropack.rsi
    state: icon
  discipline: WarCrimes
  tier: 1
  cost: 5000
  recipeUnlocks:
  - ClothingBackpackElectropack
  - WeaponParticleDecelerator
  technologyPrerequisites:
  - RiotControlAdvanced

- type: technology
  id: MilitaryGygax
  name: research-technology-military-machinery
  icon:
    sprite: Objects/Specific/Mech/mecha.rsi
    state: gygax
  discipline: WarCrimes
  tier: 3
  cost: 10000
  recipeUnlocks:
  - GygaxHarness
  - GygaxLArm
  - GygaxRArm
  - GygaxLLeg
  - GygaxRLeg
  - GygaxCentralElectronics
  - GygaxPeripheralsElectronics
  - MechLaserWeapon
  - MechScattershotWeapon
  technologyPrerequisites:
  - RiotControlAdvanced
  - RoboticsMachines
  - PortableFission

- type: technology
  id: ModernCombatMechs
  name: research-technology-modern-combat-mechs
  icon:
    sprite: Objects/Specific/Mech/mecha.rsi
    state: durand
  discipline: WarCrimes
  tier: 3
  cost: 18000
  recipeUnlocks:
  - DurandHarness
  - DurandLArm
  - DurandRArm
  - DurandLLeg
  - DurandRLeg
  - DurandCentralElectronics
  - DurandPeripheralsElectronics
  - MechSolarisLaserWeapon
  - MechHadesWeapon
  - MechMssileWeapon
  - MechTeslaWeapon
  technologyPrerequisites:
  - MilitaryGygax