- type: technology
  id: Lightning
  name: research-technology-lightning
  icon:
    sprite: Objects/Power/light_bulb.rsi
    state: normal
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
   - LightTube
   - LightBulb
   - WarmLightBulb
  position: 2,7

- type: technology
  id: LightningAdvanced
  name: research-technology-lightning-advanced
  icon:
    sprite: Objects/Power/light_tube.rsi
    state: normal
  discipline: Service
  tier: 1
  cost: 1000
  recipeUnlocks:
   - LedLightTube
   - SodiumLightTube
   - ExteriorLightTube
   - LedLightBulb
   - DimLightBulb
  technologyPrerequisites:
   - Lightning
  position: 1,7

- type: technology
  id: Bootlegging
  name: research-technology-bootlegging
  icon:
    sprite: Objects/Consumable/Drinks/generic_jug.rsi
    state: icon
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  technologyPrerequisites:
  - ServiceMachines
  position: 2,8

- type: technology
  id: Kitchen
  name: research-technology-kitchen
  icon:
    sprite: Objects/Consumable/Food/bowl.rsi
    state: bowl
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - Ashtray
  technologyPrerequisites:
  - ServiceMachines
  position: 4,8

- type: technology
  id: Entertainment
  name: research-technology-entertainment
  icon:
    sprite: Objects/Fun/Instruments/h_synthesizer.rsi
    state: icon
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
   - SynthesizerInstrument
   - HandheldStationMap
  technologyPrerequisites:
  - ServiceMachines
  position: 3,9

- type: technology
  id: EntertainmentAdvanced
  name: research-technology-entertainment-advanced
  icon:
    sprite: Backmen/Objects/Weapons/Grenades/confetti.rsi
    state: icon
  discipline: Service
  tier: 2
  cost: 6500
  recipeUnlocks:
   - ConfettiGrenade
  position: 4,9

- type: technology
  id: Cleaning
  name: research-technology-cleaning
  icon:
    sprite: Objects/Specific/Janitorial/mop.rsi
    state: mop
  discipline: Service
  tier: 1
  cost: 500
  recipeUnlocks:
  - MopItem
  - TrashBag
  - LightReplacer
  - Holoprojector
  - WetFloorSign
  - ClothingHeadHatCone
  - SprayBottle
  - Bucket
  technologyPrerequisites:
  - ServiceMachines
  position: 4,6

- type: technology
  id: TranslationDevice
  name: research-technology-translation-device
  icon:
    sprite: Backmen/Objects/Devices/translator.rsi
    state: icon
  discipline: Service
  tier: 1
  cost: 10000
  recipeUnlocks:
  - CanilunztTranslator
  - BubblishTranslator
  - NekomimeticTranslator
  - DraconicTranslator
  - SolCommonTranslator
  - RootSpeakTranslator
  - MofficTranslator
  - ElvishTranslator
  - DwarvenTranslator
  - ShadokinTranslator
  - ValyrianStandardTranslator
  - EvePishtuTranslator
  - CarshnilTranslator
  position: 7,6

- type: technology
  id: TranslationImplanter
  name: research-technology-translation-implanter
  icon:
    sprite: Objects/Specific/Medical/implanter.rsi
    state: implanter0
  discipline: Service
  tier: 1
  cost: 7500
  recipeUnlocks:
  - BasicGalaticCommonTranslatorImplanter
  technologyPrerequisites:
  - TranslationDevice
  position: 8,6

- type: technology
  id: TranslationDeviceAdvanced
  name: research-technology-translation-device-advanced
  icon:
    sprite: Backmen/Objects/Devices/translator.rsi
    state: icon
  discipline: Service
  tier: 2
  cost: 12000
  recipeUnlocks:
  - XenoTranslator
  - AnimalTranslator
  technologyPrerequisites:
  - TranslationDevice
  position: 7,7

- type: technology
  id: TranslationImplanterAdvanced
  name: research-technology-translation-implanter-advanced
  icon:
    sprite: Objects/Specific/Medical/implanter.rsi
    state: implanter0
  discipline: Service
  tier: 2
  cost: 15000
  recipeUnlocks:
  - AdvancedGalaticCommonTranslatorImplanter
  - BubblishTranslatorImplanter
  - NekomimeticTranslatorImplanter
  - DraconicTranslatorImplanter
  - CanilunztTranslatorImplanter
  - SolCommonTranslatorImplanter
  - RootSpeakTranslatorImplanter
  - MofficTranslatorImplanter
  - ElvishStandardTranslatorImplanter
  - DwarvenStandardTranslatorImplanter
  - ShadokinStandardTranslatorImplanter
  - ValyrianStandardTranslatorImplanter
  - CarshnilTranslatorImplanter
  - EvePishtuTranslatorImplanter
  technologyPrerequisites:
  - TranslationImplanter
  - TranslationDeviceAdvanced
  position: 8,7
