- type: job
  id: BKBPLAMED
  name: job-name-silicon-BPLAMED
  description: job-description-silicon-BPLAMED
  playTimeTracker: BPLAMED
  joinNotifyCrew: false
  icon: JobIconUnknown
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: DroneBPLAMED
  whitelistRequired: true
  discordRequired: true
  startingGear: RobotGear # for char preview only
